### ISSUE TITLE
Simple Get example

### ISSUE THREAD

**Issue by mattcanty** [LabD/python-param-store#7]
I'm having a difficult time understanding how to use module given the readme's example.

Assuming I have the following keys:

`/MY_APP/RDS/USERNAME`
`/MY_APP/RDS/PASSWORD`

How would I retrieve those for use within a Lambda function. The best I can grok from the examples is as follows - where `PARAMETER_STORE_CONFIG_PATH` is `/MY_APP/`:
```
data = {
    'db_username': os.environ['PARAMETER_STORE_CONFIG_PATH'] + 'RDS/USERNAME',
    'db_password': os.environ['PARAMETER_STORE_CONFIG_PATH'] + 'RDS/PASSWORD'
}

store = EC2ParameterStore()
parameters = interpolate_dict(data, store)

db_username = parameters['db_username']
db_password = parameters['db_password']
```

The code does not error but I certainly do not get anything I expect.

Thanks

**Comment by pjstevns** [comment]
@mattcanty 

(I didn't write this module, but use it daily)

The values between the double-curlies are expanded.  In other words, for all values in the data-dict, the string between the curlies are looked up in the parameterstore as-is, albeit stripped,

so your data dict should probably look like:

`
data = {
    'db_username': '{{ MY_APP/RDS/USERNAME }}',
    'db_password': '{{ MY_APP/RDS/PASSWORD }}',
}
`
You should probably get away with string-interpolation in the template fragments.

regards,

Paul.

**Comment by mattcanty** [comment]
Thanks @pjstevns, have it working like this:

```
data = { 
    'db_username': '{{ /MY_APP/RDS/USERNAME }}',
    'db_password': '{{ /MY_APP/RDS/PASSWORD }}'
}

store = EC2ParameterStore()
parameters = interpolate_dict(data, store)

db_username = parameters['db_username']
db_password = parameters['db_password']
```
